# Generated by Django 2.1.3 on 2018-11-18 13:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('poetry', '0002_auto_20181118_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='poem',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 18, 13, 33, 47, 23869, tzinfo=utc)),
        ),
    ]
