# Generated by Django 2.1.3 on 2018-11-18 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poetry', '0003_poem_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poem',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
