# Generated by Django 2.1.3 on 2018-11-22 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poetry', '0006_auto_20181122_2123'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='author_id',
            new_name='comment_author',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='poem_id',
            new_name='comment_poem',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='pub_date',
            new_name='comment_pub_date',
        ),
    ]
