# Generated by Django 2.1.3 on 2018-11-23 17:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('poetry', '0008_sidebarinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='sidebarinfo',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 23, 17, 21, 11, 564342, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='sidebarinfo',
            name='priority',
            field=models.IntegerField(default=0),
        ),
    ]
