# Generated by Django 2.1.3 on 2018-11-23 18:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('poetry', '0009_auto_20181123_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='sidebarinfo',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='sidebarinfo',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 23, 18, 19, 37, 73818, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='sidebarinfo',
            name='link',
            field=models.CharField(default=None, max_length=512),
        ),
    ]
