# Generated by Django 2.1.3 on 2018-11-24 09:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('poetry', '0011_auto_20181123_2355'),
    ]

    operations = [
        migrations.CreateModel(
            name='aboutBasya',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_name', models.CharField(max_length=100)),
                ('full_name', models.CharField(max_length=256)),
                ('text', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='sidebarinfo',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 24, 9, 40, 43, 580016, tzinfo=utc)),
        ),
    ]
