# Generated by Django 2.1.3 on 2019-01-27 15:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('poetry', '0012_auto_20181124_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='poem',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='poetry/static/img'),
        ),
        migrations.AlterField(
            model_name='sidebarinfo',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 27, 15, 50, 6, 815639, tzinfo=utc)),
        ),
    ]
