# Generated by Django 2.1.3 on 2019-01-27 15:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('poetry', '0013_auto_20190127_1850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poem',
            name='image_name',
        ),
        migrations.AlterField(
            model_name='sidebarinfo',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 27, 15, 52, 58, 345879, tzinfo=utc)),
        ),
    ]
