# Generated by Django 2.1.3 on 2019-01-27 15:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('poetry', '0014_auto_20190127_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sidebarinfo',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 27, 15, 59, 45, 559449, tzinfo=utc)),
        ),
    ]
