# Generated by Django 2.1.3 on 2019-02-02 08:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('poetry', '0015_auto_20190127_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poem',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='img/'),
        ),
        migrations.AlterField(
            model_name='sidebarinfo',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 2, 8, 25, 54, 918171, tzinfo=utc)),
        ),
    ]
