# Generated by Django 2.1.3 on 2019-02-03 16:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('poetry', '0016_auto_20190202_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sidebarinfo',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 3, 16, 26, 32, 413842, tzinfo=utc)),
        ),
    ]
