# Generated by Django 2.2 on 2019-10-17 18:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('poetry', '0017_auto_20190203_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sidebarinfo',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 17, 18, 48, 16, 301287, tzinfo=utc)),
        ),
    ]
