# Generated by Django 2.1.3 on 2019-02-07 19:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('poetry', '0017_auto_20190203_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sidebarinfo',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 7, 19, 17, 17, 406947, tzinfo=utc)),
        ),
    ]
