# Generated by Django 2.2 on 2019-10-17 18:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('poetry', '0018_auto_20190207_2217'),
    ]

    operations = [
        migrations.CreateModel(
            name='YoutubeVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=512)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='sidebarinfo',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 17, 18, 13, 48, 511162, tzinfo=utc)),
        ),
    ]
