# Generated by Django 2.2 on 2019-10-17 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poetry', '0020_auto_20191017_2134'),
        ('poetry', '0018_auto_20191017_2148'),
    ]

    operations = [
    ]
